### ISSUE TITLE
[Question] W(n) = sqrt(n).W(sqrt(n))+1

### ISSUE THREAD

**Issue by thaodod** [kaist-cp/cs500-2019s#11]
I think this recurrence is balanced. But I don't know how to determine how many levels (depth of the tree).
because : W(n) --> W(n^1/2) --> W(n^1/4) --> W(n^1/8) --> W(~1).
Eg: W(16)--> W(4) --> W(2) --> W(sqrt(2)).
so I have to solve this equation: n^(1/2^i) ~= 1.
But I don't know how. Log(1)=0 and Log1(a) is undefined.

**Comment by jaeseok-huh** [comment]
I think it's leaf dominated since 1 <= sqrt(n).
Also, it would be practically useful to make the domain of W be integers with floor/ceiling function. Then, you won't have to worry about that.

**Comment by thaodod** [comment]
Yes. I agree with @jason-huh about leaf dominated point but we still have to determine the number of leave ? About floor/ceiling I also thought about that but I don't know how to calculate with them.

**Comment by jeehoonkang** [comment]
Let's analyze each level of the recursion tree whose root is calculating W(n).

- At level 0 (i.e. at the root), there is 1 node that calculates W(n).
- At level 1, there are n^(1-1/2) nodes that calculate W(n^(1/2)).  (Let's abuse the notation so that we can say "n^(1-1/2) nodes" even if n^(1-1/2) is not an integer, as the same way as we omitted flooring and ceiling.)
- At level 2, there are n^(1-(1/2)^2) nodes that calculate W(n^((1/2)^2)).
- ...
- At level i, there are n^(1-(1/2)^i) nodes that calculate W(n^((1/2)^i)).


Now let's analyze the depth.

- I will assume that W(2) is a constant, because the recursion should end somewhere.  That means, we will regard W(2) as a leaf.

- Now let's find out the depth `d` of the recursion tree.  Level i consists of n^(1-(1/2)^i) nodes that calculate W(n^((1/2)^i)), so we have n^((1/2)^d) = 2.  By simplification, we have d = lg lg n.

By the above arguments, we have n^(1-(1/2)^(lg lg n)) = n^(1-(1/lg n)) leaves.  So W(n) = O(n^(1-(1/lg n))).

**Comment by thaodod** [comment]
Thanks.
