### ISSUE TITLE
Work of filter

### ISSUE THREAD

**Issue by HaritzPuerto** [kaist-cp/cs500-2019s#20]
Hello,

I have a question about the work of filter.

In the book it is stated that the work of filter is as follows:
![image](https://user-images.githubusercontent.com/2658728/55214595-766dd100-523a-11e9-8070-0544fbecdef1.png)

And its implementation is:
![image](https://user-images.githubusercontent.com/2658728/55214626-91d8dc00-523a-11e9-8b07-003b2ec395b0.png)

I think the work to obtain b is sum(W(f(x))) but we should also add the work of flatten to the total work of filter, right? So I think we should add |a| + sum(x) where x \in a

Thank you

**Comment by jeehoonkang** [comment]
- For the implementation of `filter` you provided, you're right.  The `|a|` term should be considered as well.
- But for the purpose of (asymptotic) analysis of `filter`, `1 + sum_{x \in a} W(f(x))` is enough because the sum `>= |a|` (the inequality from the fact that `W(X) >= 1` for all computation `X`).

**Comment by HaritzPuerto** [comment]
Thank you. Now it is clear :)
