### ISSUE TITLE
Work BFS sequence indexes

### ISSUE THREAD

**Issue by HaritzPuerto** [kaist-cp/cs500-2019s#22]
Hi,

Why the work of BFS using a sequence of indexes to represent F is |E|? I cannot understand it. BFSInner is still called |V| times, right? So I guess |V| should be there too.

Thank you

**Comment by cyron1259** [comment]
I guess the most confusing part is line 9.

First, the following equation holds.
sum{|NG+(V_i)|}=|E|

Since flatten invokes union (and union invokes combine), the amount of work in a BFSInner function is the sum of |NG+(V_i)| for all V_i in F.

And since every vertex is called only once, the total amount of work is O(sum{|NG+(V_i)|}) for all V_i, which is O(|E|).

I wrote this real quick, so there could be some mistakes or weak points. Correct me if there is any!

**Comment by HaritzPuerto** [comment]
Thanks. It's clear now :)
