### ISSUE TITLE
Question about BFS(Representing F as Index Sequence)

### ISSUE THREAD

**Issue by kobowon** [kaist-cp/cs500-2019s#24]
Hi, I have four questions about BFS(Representing F as Index Sequence)

Q1. I wonder how N_{G} (Fi) is implemented.
 I think N_{G} (Fi) = convert(map(lamda f.(row of f in adjacent matrix) Fi)), so total work of map = O(|V|), total work of convert = O(|V|^2). I wonder if this is right or not.

Q2. What is work and span of X U F?
I think X U F = union (convert X) F. so work of (XUF) is O(|V|), span is 1. I wonder if this is right or not.

Q3. I wonder why work is O(|E|).
I think most dominant part of work and span is line 9. And line 9 is divided into two parts(Constructing N_{G} (Fi) as index sequence, flatten N_{G} (Fi))
- I think work of constructing  N_{G} (Fi) is O(|V^2|) (Question1)
- And flatten N_{G} (Fi) = reduce union empty N_{G} (Fi). work of union(append) = O(|V|), and reduce it at most N_{G} (Fi) times. So I think totally work of flatten is O(|V| x |E|).

Why work of line 9 is O(|E|)?   

Q4. Why span of DFS is O(dlg|V|)?

Please let me know. Thanks!

**Comment by CauchyComplete** [comment]
I was about to write the almost same question. Since you already wrote it, I'll add my question here.

**Comment by CauchyComplete** [comment]
I was about to write the almost same question. Since you already wrote it, I'll add my question here.
I'll denote BFS representing F as a boolean sequence by BFS1 and BFS representing F as an index sequence by  BFS2. 
1. I also wonder why BFS2 takes E work. 
2. If BFS2 invokes Inner at most d times, then why we assumed Inner is invoked at most V times when we are analyzing BFS1? We could say BFS1 also invokes Inner at most d times then.
3. I think we need to decide how to implement E.

**Comment by hyunsoo0o0o0** [comment]
> Hi, I have four questions about BFS(Representing F as Index Sequence)
> 
> Q1. I wonder how N_{G} (Fi) is implemented.
> I think N_{G} (Fi) = convert(map(lamda f.(row of f in adjacent matrix) Fi)), so total work of map = O(|V|), total work of convert = O(|V|^2). I wonder if this is right or not.
> 
> Q2. What is work and span of X U F?
> I think X U F = union (convert X) F. so work of (XUF) is O(|V|), span is 1. I wonder if this is right or not.
> 
> Q3. I wonder why work is O(|E|).
> I think most dominant part of work and span is line 9. And line 9 is divided into two parts(Constructing N_{G} (Fi) as index sequence, flatten N_{G} (Fi))
> 
> * I think work of constructing  N_{G} (Fi) is O(|V^2|) (Question1)
> * And flatten N_{G} (Fi) = reduce union empty N_{G} (Fi). work of union(append) = O(|V|), and reduce it at most N_{G} (Fi) times. So I think totally work of flatten is O(|V| x |E|).
> 
> Why work of line 9 is O(|E|)?
> 
> Q4. Why span of DFS is O(dlg|V|)?
> 
> Please let me know. Thanks!

N_G(v) can be precomputed in O(E) work. So N_G(Fi) = reduce union N_G Fi has O(sum(deg(vi))) work (where vi is a vertex in Fi). Summing up for all iteration, this line has total work of O(sum(deg(vi))) = O(E).

**Comment by jeehoonkang** [comment]
- Q1: N+_G(F) =
    let F' = map (lambda f. [row of f in adjacent list) F in
    flatten F'.

  No conversion is needed if we use adjacent list.  The work = O(|F| + |N+_G(F)|), and span = O(lg |F|).

- Q2: X U F can be implemented with inject X (map i. (i,true) F).  The work = O(|V|) and span = O(1).

  But we can further optimize it by exploiting the fact that X is no longer used after assigning X' = X U F.
  We can "reuse" the memory allocation for X, thereby saving the cost of copying the contents of X.
  This optimization yields an algorithm of X U F with work = O(|F|) and span = O(1).

- Q3, A4: As you said, line 9 dominates the work and span.  To get O(|E|) and O(d lg |V|) work and span, we need a more precise analysis.

  For any vertex v, it is in F for exactly one invocation of BFSInner.
  So the total work = O(sum of (|F| + |N+_G(F)|) for invocations of BFSInner) = O(|V| + |E|).
  And The total span = O(d lg |V|), since the span of line 9 is O(lg |F|) <= O(lg |V|).

- @CauchyComplete Q2: Yes, BFS1 invokes BFSInner at most d times, too, and the span is O(d lg |V|) as well as O(|V| lg |V|).

- @CauchyComplete Q3: Yes, let's assume it's adjacent list.

**Comment by jaeseok-huh** [comment]
See #31 . To keep `F` as a sorted index sequence, duplicative indices shall be removed.
