### ISSUE TITLE
Question about BFS when F is represented as index sequence

### ISSUE THREAD

**Issue by qkrclrl701** [kaist-cp/cs500-2019s#30]
In the answer of the Q&A before, It says:
F' = N_G(F) \ X'
Requires O(|F| + N_G(F)) work and it is dominant, so by adding d number of such terms, we have O(|V| + |E|) work.
However, suppose E = {(v1, v2), ... , (v_(n-1), v_n)} and it starts from v1.
Then, we have d = |V| and, since X' = X union F requires O(|V|) work, total work would be O(|V|^2) which is not equal to O(|V| + |E|).
Also, is_empty(X)'s implementation seems wrong, since X is boolean sequence. I think it should be the same as the implementation defined in page 1.
(Which means, even if we optimize X union F by not copying elements of X to X', checking if X is empty for d times requires O(|V|^2) work already.)

**Comment by cyron1259** [comment]
The only usage of is_empty is line 5: 'if F==NULL' and F is an index sequence, so I think it's just a little typo (X instead of F). There's no problem with the implementation.

**Comment by HaritzPuerto** [comment]
I fully agree with you @qkrclrl701 about the total work. Actually, I made a small experiment to see it myself and convince me and yes, the work is just as you said
![image](https://user-images.githubusercontent.com/2658728/56009282-40d8e580-5d1a-11e9-94fb-0980b1ef1830.png)
I think we need a better implementation of the union. Due to inject, we need to do a copy of X
From the book:
![image](https://user-images.githubusercontent.com/2658728/56009462-c78dc280-5d1a-11e9-888b-bfb435a74396.png)

I think the solution is to use an ephemeral boolean sequence to represent X as proposed in the book. In chapter 17 ephemeral data structures are explained. Basically, since we use the sequence only once (in each resursive call) and then we create a new copy, we could reuse it instead of making a copy in each recursive call. This way work and span for update would be constant. Actually, the Professor talked about this in a previous issue but I think he proposed it as an optimization. But after this, I think we do need it. 

Are our thoughts correct? Or are we missing something? Should we use ephemeral data structures in the exam? @jeehoonkang 

Thank you

**Comment by jeehoonkang** [comment]
> Then, we have d = |V| and, since X' = X union F requires O(|V|) work, total work would be O(|V|^2) which is not equal to O(|V| + |E|).

Please see my answer to "Q2" here: https://github.com/kaist-cp/cs500-2019s/issues/24#issuecomment-481463473  In short, we can basically reuse `X` (because `X` is no longer used here) and thus can implement `X union F` with `O(F)` work.

FYI, I promised in the last session that I will not ask questions about this kind of memory allocation "reusing" in the cost analysis.


> Also, is_empty(X)'s implementation seems wrong, since X is boolean sequence. I think it should be the same as the implementation defined in page 1.

Thank you for pointing out the bug.  I just fixed it.
