### ISSUE TITLE
Discussion on Quiz Solution

### ISSUE THREAD

**Issue by jaeseok-huh** [kaist-cp/cs500-2019s#38]
@jeehoonkang thank you for handing out a solution for the quiz. It has helped my studying a lot. I'd like to discuss a few points about that.

For the future readers, I'm referring to 658f0c923af0789fdefc8ab702f308770f1fb46c.

In problem 2, I think, the second condition *Inclusive* is redundant because it's a sufficient condition of *Join*.

In problem 4, the answer for *SimplPaths(G)* allows for the initial and terminal vertex to coincide. However, the textbook says in page 39, 

> A simple path is a path with no repeated vertices. 

Regarding problem 5, please see #25, which was closed by the author seemingly without your attention.

It would be appreciated if you could give me a feedback about above.

Best,

**Comment by jeehoonkang** [comment]
@jason-huh Thank you for summarizing the bugs.  I fixed problems 2 and 5, but left problem 4 as is now.  I intentionally allow the initial and final vertices to coincide, which may diverges from the textbook, because I feel it's more consistent: I think *simple cycle*, which has the same initial and final vertices, should be a simple path.
