### ISSUE TITLE
Question about locking

### ISSUE THREAD

**Issue by BoSamothrace** [kaist-cp/cs500-2019s#57]
Based on the definition of lock() and unlock(), in the example of the slide, after we adding the lock()unlock() in threadA, the order of the instructions have been guaranteed already. Why do we need the lock()unlock() in threadB? 

Any help would be appreciated.

**Comment by BoSamothrace** [comment]
I mean the example in the “Common wisdom:locking” slide

**Comment by jeehoonkang** [comment]
That's a good question.  That's because, very strangely, relaxed hardware like ARM or RISC-V may (speculatively) reorder the read from F and X in thread B.  If it happens, thread B may read X=0 and then read F=1, failing to satisfy the assertion.

Shorter answer: if not confident, just protect all accesses to shared locations using locks.

**Comment by BoSamothrace** [comment]
I see I see. Thank you~
