### ISSUE TITLE
Question Example 1.7 from the book

### ISSUE THREAD

**Issue by HaritzPuerto** [kaist-cp/cs500-2019s#6]
![image](https://user-images.githubusercontent.com/2658728/53877764-6143bf00-404d-11e9-9870-eb8c9f87ca27.png)

I don't understand why "+5" is written there. I think we need no more than 150/3 minutes. I mean, we have 30 eggs and 3 cooks. Assuming that one cook can cook one egg at a time, we need 50 minutes, right? I don't understand why 55 minutes is stated.

Thank you

**Comment by jaeseok-huh** [comment]
I had the same question and concluded that it’s from the constant 1 when we perform parallelizing. In reality, it is usually not a constant but in theory (at least in the textbook) it is assumed so.

**Comment by jeehoonkang** [comment]
I agree with @jason-huh.  At the beginning, we need to distribute eggs to cooks, which takes some time, so that we cannot "perfectly" parallelize cooking by evenly distributing eggs to cooks.  That means a cook needs to process 11 eggs, taking 55 minutes.

**Comment by HaritzPuerto** [comment]
ahhhh so we are assuming that distributing eggs takes the same time as cooking one egg. 

Thank you

**Comment by jeehoonkang** [comment]
Thinking again, I think my argument is wrong.  In reality, we can easily distribute 30 eggs to 3 cooks in 1 minute, after which each cook can process 10 eggs in 50 minutes.  In total, only 51 minutes take, instead of 55 minutes.

I think it's a bug in the book, and will report it at the end of this semester.  Thank @HaritzPuerto for reporting this issue.
