### ISSUE TITLE
concurrent linked list insertion

### ISSUE THREAD

**Issue by fairy-of-9** [kaist-cp/cs500-2019s#60]
Hi...

![제목 없음](https://user-images.githubusercontent.com/37280914/58953396-4c540480-87d1-11e9-8bfa-76a0fcbcf963.png)

I don't know what the letters in the red square are.
I'm sorry... I didn't concentrate in a lecture...

Thanks

**Comment by jeehoonkang** [comment]
Succeeded

**Comment by fairy-of-9** [comment]
Thank you...!!

**Comment by giangnguyen2412** [comment]
@jeehoonkang in this case, if ThreadA succeeded, the Y.next will be changed from Z to new of ThreadA, then threadB executes, but we still keep the condition Y.next.compare_and_set(Z, new). I am supposing that threadB will always fail because Y.next is now new-of-threadA, not Z anymore.

Is this correct?

**Comment by jeehoonkang** [comment]
@luulinh90s I forget the context of this..  I assume two threads concurrently try to insert a node, right?  Then yes, if thread A succeeded in CAS, then thread B will not be able to succeed in CAS too.

**Comment by giangnguyen2412** [comment]
Then in the case of insertion, we will not try again at all, right?
Furthermore, in case of removal and insertion are performed at the same time, if Insertion-thread (thread trying to insert) detects Z is marked to remove, we also don't need to try again because at this time, Insertion will always fail, am I right?
