### ISSUE TITLE
Deletion in a lock-free linked list, in case where the second CAS failed

### ISSUE THREAD

**Issue by hyunsoo0o0o0** [kaist-cp/cs500-2019s#63]
![image](https://user-images.githubusercontent.com/12685285/59080335-2474b600-8923-11e9-8cd6-97aae2965809.png)

Deletion is done by first marking the node to be deleted using the first compare-and-set (CAS) operation, and then re-linking adjacent nodes using the second CAS.
What if the second CAS fails? As I heard from @jeehoonkang, once a node is marked as removed, it cannot be unmarked because marked node must eventually be removed. So aborting deletion is not an option, I guess.

**Comment by HaritzPuerto** [comment]
Hi! Could you explain in which situation the CAS (2) would fail? I can't come up with an example. On the other hand,  maybe I am wrong, but I think I found a problem in our implementation of removal.

Let's suppose we have this linked list:
x-> y -> z -> w
We have 2 threads: T1 wants to remove y and T2 wants to remove z

and let's suppose the following execution:
T1
z = y.next
fetch_add(y.next,1) //mark as 1
T2
w = z.next
fetch_add(z.next) //mark as 1
y.next.cas(z,w) // at this point we have x -> y -> w
T1
x.next.cas(y,z) // it does finish because x.next and y are the same memory location. Note we changed y.next but not the memory location of y. So after this, we have x -> z -/> w and  y -> w (note -/> means marked link)

Is my reasoning ok? If so, I think we need to check somehow the that the next node of y is w in the CAS of T1

**Comment by hyunsoo0o0o0** [comment]
@HaritzPuerto 
I think the second CAS might fail if both deletion of z and insertion between y and z occurs concurrently, but I'm not sure. I'm sure that there is a failure case because if it is always successful, there's no point using CAS instead of plain write operation.

About the problem you found, I agree with you. I think the problem arises from the last CAS, where x is linked to marked node. I don't understand how deletion can work properly without preventing such behaviors.

**Comment by HaritzPuerto** [comment]
I think there is no problem if we delete z and insert a new node between y and z at the same time given this linked list:
x-> y -> z -> w
Thread 1 will do the delete and Thread 2 will do the insert

T1
w = z.next
fetch_add(z.next, 1) //mark z as removed
T2
z = y.next
if z is marked as removed, stop
Insertion is not done, T1 finished succesfully.

On the other hand, if we try to delete z and insert a new node between z and w, then, I think we get inconsistent results. Note this is the example of the slides
T1
w = z.next
fetch_add(z.next, 1)
T2
w = z.next
if w is marked, stop 
//w is not mark, so continue
new = alloc.node()
z.next.cas(w, new) //I am assuming that the boolean flag we add to z.next do not affect to cas since cas is comparing the memory address of z.next and w, which are the same.
new.next = w 
//so we have x -> y -> z -> new -> w
T1
y.next.cas(z, w) //y.next is the same as z, so we can execute cas
//so we have x-> y -> w and z -> new -> w

Does it make sense what I wrote? Thanks!!

**Comment by hyunsoo0o0o0** [comment]
@HaritzPuerto 
What if T2 proceeds before marking is done by T1? So, it will goes like this:

| T1 (delete z) | T2 (insert bet. y and z) |
|---------------|--------------------------|
| w = z.next ||
|| z = y.next |
|| if z is marked, stop // not marked |
|| new = new node(value) |
|| new.next = z |
| fetch_add(z.next, 1) // mark removed ||
|| y.next.CAS(z, new) // successful |
| y.next.CAS(z, w) // failed ||
| ??? ||

 I think deleting z and inserting between z and w is not a problem. I guess `z.next.cas(w, new)` should fail because marking do affect CAS.

**Comment by HaritzPuerto** [comment]
I totally agree with you. I also think T1 would fail

Thanks for pointing out that marking does affect CAS :)

**Comment by luulinh90s** [comment]
@HaritzPuerto @ppnchb I wanna comment that to set the flag, we use **`fetch_or`** NOT **`fetch_add`**.

**Comment by luulinh90s** [comment]
@HaritzPuerto @ppnchb I wanna comment that to set the flag, we use **`fetch_or`** NOT **`fetch_add`**. Anyway, in this situation, may both of them could be the same, need to inquiry the prof for sure.

**Comment by fairy-of-9** [comment]
@HaritzPuerto 
Hi, 
I have a question about your comment.

******************************
Let's suppose we have this linked list:
x-> y -> z -> w
We have 2 threads: T1 wants to remove y and T2 wants to remove z

and let's suppose the following execution:
T1
z = y.next
**fetch_add(y.next,1)** //mark as 1
T2
w = z.next
fetch_add(z.next) //mark as 1
**y.next.cas(z,w)** // at this point we have x -> y -> w
T1
x.next.cas(y,z) // it does finish because x.next and y are the same memory location. Note we changed y.next but not the memory location of y. So after this, we have x -> z -/> w and y -> w (note -/> means marked link)
******************************

It is your first comment.
y.next is different from Z. because it is marked. (**fetch_add(y.next,1)**)
so I think **y.next.cas(z,w)** would failed.
Am I miss something?

**Comment by HaritzPuerto** [comment]
Hi @fairy-of-9 thanks for pointing it out. A few hours ago, I thought that CAS was not affected by marking because marking is like a boolean flag and the data is still in the same memory spot, but yeah, marking does change the less significant bit, so even though the data is in the same spot, marking does change a little bit the pointer. I was confused because in the insert we check with an "if instruction" whether z is marked or not, but it is a totally different case and it is the only way in the "insert" case.

**Comment by jeehoonkang** [comment]
We will write the algorithm to ensure the following properties:

- If a node is marked as deleted, it is indeed logically deleted.  In other words, even though the node is physically present in the list, it is regarded as logically deleted.
- If the second CAS fails, then another thread did or will delete the node.

**Comment by hyunsoo0o0o0** [comment]
@jeehoonkang Thanks. About the second property, does it implies that any thread which found logically deleted node during an operation should try physically deleting the node?

**Comment by jeehoonkang** [comment]
@ppnchb Yes, any threads may attempt to physically delete the node if it's marked as logically deleted.

**Comment by HaritzPuerto** [comment]
In the second post here I wrote about the two deletion case. I made I mistake then and now I will fix it.

Let's suppose we have this linked list:
x-> y -> z -> w
We have 2 threads: T1 wants to remove y and T2 wants to remove z

and let's suppose the following execution:
T1
z = y.next
fetch_add(y.next,1) //mark as 1
T2
w = z.next
fetch_add(z.next) //mark as 1
y.next.cas(z,w) // fails because y.next is marked
T1
x.next.cas(y,z) // it does finish. So after this, we have x -> z -/> w (note -/> means marked link)

So z is considered as removed but it is still present in the list. I join the question of @ppnchb and I would also ask if maybe we have a garbage collector that is in charge of removing all this "trash" instead of what @ppnchb proposed.

Thank you!

**Comment by jeehoonkang** [comment]
@HaritzPuerto In iteration, a thread tries to physically delete the nodes that are already logically deleted.  Calling `free()` for that node is another question, though, which we didn't cover in the class.

So `delete()` has three steps:
- Logical deletion: marking the node as deleted.  After logically deleted, a node is regarded as actually deleted and is invisible to the programmers.
- Physical deletion: removing the node from the list.  By (possibly concurrently) iterating threads.
- `free()`ing: returning the resources to e.g. libc

**Comment by fairy-of-9** [comment]
아래의 질문은 https://github.com/kaist-cp/cs500-2019s/issues/75#issue-453896124 여기서 해결했습니다.



@HaritzPuerto
Hi,
I have a question about your comment.

****

T1
w = z.next
fetch_add(z.next, 1) //mark z as removed
T2
z = y.next
if z is marked as removed, stop
Insertion is not done, T1 finished succesfully.

****
It is your comment.
I think, z(=y.next) is not marked in T2.
becuase, T1 is marking to z.next.



****
T1
w = z.next
fetch_add(z.next, 1)
T2
w = z.next
if w is marked, stop
//w is not mark, so continue
****
and I think, T2 doesn't proceed.
because, w = z.next(already marked).

Am I miss something?

**Comment by jeehoonkang** [comment]
@fairy-of-9 I quite cannot understand your comment..  Would you please elaborate on your question?

**Comment by jeehoonkang** [comment]
At this stage of semester, I'd like to close tech-related issues.
