### ISSUE TITLE
correctness of odd-even sort

### ISSUE THREAD

**Issue by CauchyComplete** [kaist-cp/cs500-2019s#64]
Lecture note says that proof of (ii) Co[i+1] <= Ce[i+1] is trivial. But I don't think so. If (Co,Ce) is an odd-even split of some sequence, then it is trivial. But since it's not, I think it's not trivial. So if you think it's trivial, please show the proof. It must be easy since it's trivial :D

**Comment by thaodod** [comment]
Up so. I also find it hard, not trivial.

**Comment by HaritzPuerto** [comment]
I don't think the proof is trivial, but I think it can be proven using the lemma in a very similar way to (III)

**Comment by CauchyComplete** [comment]
@HaritzPuerto Then please show me cuz I failed

**Comment by HaritzPuerto** [comment]
Let me know if I am wrong, but I think it is as follows

 Ce[i+1] = max (Ae[j], Be[i+1-j])   by lemma 
 ">=" max(Ao[j], Bo[i+1-j])    by def of Ao, Bo, Ae, Be;  Ae[j-1] <= Ao[j] <= Ae[j]  
 ">=" Co[i+1]


Note that the index of A and B start at 1, so A[1] is the smallest one in A and is odd, so A[1] <= Ae[1]

Note I wrote  ">=" because markdown interprets ">" as a command if it is at the beggining of a new line. writing the quotes I can show the > symbol. You can just ignore the quotes

**Comment by jeehoonkang** [comment]
I think @HaritzPuerto 's proof is perfect.  Thanks.

**Comment by CauchyComplete** [comment]
Thanks! I will keep it open for other classmates.

**Comment by jeehoonkang** [comment]
At this stage of semester, I'd like to close tech-related issues.
